import 'dart:io';

const leagues = <int>[
  39,
  61,
  140,
  78,
  135,
  94,
  88,
  144,
  179,
  203,
  197,
  119,
  207,
  218,
  40,
  62,
  136,
  79,
  141,
  106,
  210,
  209,
  283,
  253,
  71,
  128,
  262,
  307,
  98,
  188,
];

const outputPath = '/tmp/lector_api_football_cron.sql';
const supabaseFunctionBase =
    'https://ednvvxxvlawaagjyshkj.supabase.co/functions/v1';

void main() {
  final env = _readDotEnv(File('.env'));
  final syncSecret = env['API_FOOTBALL_SYNC_SECRET'];
  if (syncSecret == null || syncSecret.trim().isEmpty) {
    stderr.writeln('Missing API_FOOTBALL_SYNC_SECRET in .env');
    exitCode = 1;
    return;
  }

  final today = DateTime.now().toUtc();
  final feedStart = _dateOnly(today);
  final feedEnd = _dateOnly(today.add(const Duration(days: 3)));
  final collectionStart = _dateOnly(today.subtract(const Duration(days: 2)));
  final collectionEnd = feedEnd;
  final buffer = StringBuffer()
    ..writeln('-- Generated by tool/generate_supabase_cron_sql.dart')
    ..writeln('-- Paste this into Supabase SQL Editor.')
    ..writeln('-- It stores API_FOOTBALL_SYNC_SECRET in cron.job command text.')
    ..writeln()
    ..writeln('create extension if not exists pg_cron with schema extensions;')
    ..writeln('create extension if not exists pg_net with schema extensions;')
    ..writeln()
    ..writeln(r'do $$')
    ..writeln('declare')
    ..writeln('  job record;')
    ..writeln('begin')
    ..writeln(
      "  for job in select jobname from cron.job where jobname like 'api-football-league-%' or jobname = 'api-football-build-snapshot'",
    )
    ..writeln('  loop')
    ..writeln('    perform cron.unschedule(job.jobname);')
    ..writeln('  end loop;')
    ..writeln('end')
    ..writeln(r'$$;')
    ..writeln();

  for (var index = 0; index < leagues.length; index += 1) {
    final leagueId = leagues[index];
    final minuteOffset = index * 4;
    final hour = minuteOffset ~/ 60;
    final minute = minuteOffset % 60;
    buffer
      ..writeln('select cron.schedule(')
      ..writeln("  'api-football-league-$leagueId',")
      ..writeln("  '$minute $hour * * *',")
      ..writeln(r'  $$')
      ..writeln('  select net.http_post(')
      ..writeln("    url := '$supabaseFunctionBase/api-football-sync',")
      ..writeln('    headers := jsonb_build_object(')
      ..writeln("      'Content-Type', 'application/json',")
      ..writeln("      'Authorization', 'Bearer ${_sql(syncSecret)}'")
      ..writeln('    ),')
      ..writeln('    body := jsonb_build_object(')
      ..writeln("      'league_ids', jsonb_build_array($leagueId),")
      ..writeln("      'bookmaker_id', 16,")
      ..writeln("      'window_start', '$collectionStart',")
      ..writeln("      'window_end', '$collectionEnd',")
      ..writeln("      'api_request_delay_ms', 750,")
      ..writeln("      'include_team_statistics', true,")
      ..writeln("      'include_recent_form', true,")
      ..writeln("      'include_expected_goals', true,")
      ..writeln("      'recent_form_days_back', 180,")
      ..writeln("      'recent_form_matches', 5")
      ..writeln('    ),')
      ..writeln('    timeout_milliseconds := 300000')
      ..writeln('  ) as request_id;')
      ..writeln(r'  $$')
      ..writeln(');')
      ..writeln();
  }

  buffer
    ..writeln('select cron.schedule(')
    ..writeln("  'api-football-build-snapshot',")
    ..writeln("  '15 2 * * *',")
    ..writeln(r'  $$')
    ..writeln('  select net.http_post(')
    ..writeln("    url := '$supabaseFunctionBase/build-match-feed-snapshot',")
    ..writeln('    headers := jsonb_build_object(')
    ..writeln("      'Content-Type', 'application/json',")
    ..writeln("      'Authorization', 'Bearer ${_sql(syncSecret)}'")
    ..writeln('    ),')
    ..writeln('    body := jsonb_build_object(')
    ..writeln("      'league_ids', jsonb_build_array(${leagues.join(',')}),")
    ..writeln("      'bookmaker_id', 16,")
    ..writeln("      'window_start', '$feedStart',")
    ..writeln("      'window_end', '$feedEnd',")
    ..writeln("      'recent_form_days_back', 180,")
    ..writeln("      'recent_form_matches', 5")
    ..writeln('    ),')
    ..writeln('    timeout_milliseconds := 300000')
    ..writeln('  ) as request_id;')
    ..writeln(r'  $$')
    ..writeln(');')
    ..writeln()
    ..writeln('select jobid, jobname, schedule, active')
    ..writeln('from cron.job')
    ..writeln("where jobname like 'api-football-%'")
    ..writeln('order by jobname;');

  File(outputPath).writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote $outputPath');
}

Map<String, String> _readDotEnv(File file) {
  if (!file.existsSync()) {
    return {};
  }
  final values = <String, String>{};
  for (final line in file.readAsLinesSync()) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) {
      continue;
    }
    final separator = trimmed.indexOf('=');
    if (separator <= 0) {
      continue;
    }
    final key = trimmed.substring(0, separator).trim();
    var value = trimmed.substring(separator + 1).trim();
    if (value.length >= 2 &&
        ((value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'")))) {
      value = value.substring(1, value.length - 1);
    }
    values[key] = value;
  }
  return values;
}

String _dateOnly(DateTime value) {
  final month = value.month.toString().padLeft(2, '0');
  final day = value.day.toString().padLeft(2, '0');
  return '${value.year}-$month-$day';
}

String _sql(String value) => value.replaceAll("'", "''");
