import 'dart:io';

import 'package:copilot/features/onboarding/domain/decision_profile_catalogs.dart';

const leagues = RuntimeCompetitionCatalog.apiFootballLeagueIds;

const cronOutputPath = '/tmp/lector_api_football_cron.sql';
const runNowOutputPath = '/tmp/lector_api_football_run_now.sql';
const supabaseFunctionBase =
    'https://ednvvxxvlawaagjyshkj.supabase.co/functions/v1';

void main() {
  final env = _readDotEnv(File('.env'));
  final syncSecret = env['API_FOOTBALL_SYNC_SECRET'];
  if (syncSecret == null || syncSecret.trim().isEmpty) {
    stderr.writeln('Missing API_FOOTBALL_SYNC_SECRET in .env');
    exitCode = 1;
    return;
  }

  final cronBuffer = StringBuffer()
    ..writeln('-- Generated by tool/generate_supabase_cron_sql.dart')
    ..writeln('-- Installs the daily API-Football orchestrated league cron.')
    ..writeln('-- Paste this into Supabase SQL Editor.')
    ..writeln('-- It stores API_FOOTBALL_SYNC_SECRET in cron.job command text.')
    ..writeln('-- Windows are computed by daily-football-sync.')
    ..writeln()
    ..writeln('create extension if not exists pg_cron with schema extensions;')
    ..writeln('create extension if not exists pg_net with schema extensions;')
    ..writeln()
    ..writeln(r'do $$')
    ..writeln('declare')
    ..writeln('  job record;')
    ..writeln('begin')
    ..writeln('  for job in')
    ..writeln('    select jobname')
    ..writeln('    from cron.job')
    ..writeln("    where jobname like 'api-football-%'")
    ..writeln("      and jobname not like 'api-football-run-now-%'")
    ..writeln('  loop')
    ..writeln('    perform cron.unschedule(job.jobname);')
    ..writeln('  end loop;')
    ..writeln('end')
    ..writeln(r'$$;')
    ..writeln();

  final runNowBuffer = StringBuffer()
    ..writeln('-- Generated by tool/generate_supabase_cron_sql.dart')
    ..writeln(
      '-- Runs the full API-Football MVP scope once, staggered by league.',
    )
    ..writeln(
      '-- Paste this into Supabase SQL Editor after installing/deploying.',
    )
    ..writeln(
      '-- It stores API_FOOTBALL_SYNC_SECRET in temporary cron commands.',
    )
    ..writeln('-- Each one-shot job unschedules itself after firing.')
    ..writeln('-- Windows are computed by daily-football-sync.')
    ..writeln()
    ..writeln('create extension if not exists pg_cron with schema extensions;')
    ..writeln('create extension if not exists pg_net with schema extensions;')
    ..writeln()
    ..writeln(r'do $$')
    ..writeln('declare')
    ..writeln('  job record;')
    ..writeln('begin')
    ..writeln(
      "  for job in select jobname from cron.job where jobname like 'api-football-run-now-%'",
    )
    ..writeln('  loop')
    ..writeln('    perform cron.unschedule(job.jobname);')
    ..writeln('  end loop;')
    ..writeln('end')
    ..writeln(r'$$;')
    ..writeln();

  for (var index = 0; index < leagues.length; index += 1) {
    final leagueId = leagues[index];
    final dailyMinuteOffset = index * 4;
    final dailyHour = dailyMinuteOffset ~/ 60;
    final dailyMinute = dailyMinuteOffset % 60;
    cronBuffer
      ..writeln('select cron.schedule(')
      ..writeln("  'api-football-league-$leagueId',")
      ..writeln("  '$dailyMinute $dailyHour * * *',")
      ..writeln(r'  $$')
      ..writeln('  select net.http_post(')
      ..writeln("    url := '$supabaseFunctionBase/daily-football-sync',")
      ..writeln('    headers := jsonb_build_object(')
      ..writeln("      'Content-Type', 'application/json',")
      ..writeln("      'Authorization', 'Bearer ${_sql(syncSecret)}'")
      ..writeln('    ),')
      ..writeln('    body := jsonb_build_object(')
      ..writeln("      'league_ids', jsonb_build_array($leagueId),")
      ..writeln("      'bookmaker_id', 16,")
      ..writeln("      'results_days_back', 2,")
      ..writeln("      'future_days', 3,")
      ..writeln("      'api_request_delay_ms', 750,")
      ..writeln("      'include_team_statistics', true,")
      ..writeln("      'include_recent_form', true,")
      ..writeln("      'include_expected_goals', true,")
      ..writeln("      'recent_form_days_back', 180,")
      ..writeln("      'recent_form_matches', 5")
      ..writeln('    ),')
      ..writeln('    timeout_milliseconds := 300000')
      ..writeln('  ) as request_id;')
      ..writeln(r'  $$')
      ..writeln(');')
      ..writeln();

    final runNowSyncJob = 'api-football-run-now-league-$leagueId';
    final runNowSyncOffset = dailyMinuteOffset + 1;

    runNowBuffer
      ..writeln('select cron.schedule(')
      ..writeln("  '$runNowSyncJob',")
      ..writeln('  ${_runNowScheduleSql(runNowSyncOffset)},')
      ..writeln(r'  $$')
      ..writeln('  select net.http_post(')
      ..writeln("    url := '$supabaseFunctionBase/daily-football-sync',")
      ..writeln('    headers := jsonb_build_object(')
      ..writeln("      'Content-Type', 'application/json',")
      ..writeln("      'Authorization', 'Bearer ${_sql(syncSecret)}'")
      ..writeln('    ),')
      ..writeln('    body := jsonb_build_object(')
      ..writeln("      'league_ids', jsonb_build_array($leagueId),")
      ..writeln("      'bookmaker_id', 16,")
      ..writeln("      'results_days_back', 2,")
      ..writeln("      'future_days', 3,")
      ..writeln("      'api_request_delay_ms', 750,")
      ..writeln("      'include_team_statistics', true,")
      ..writeln("      'include_recent_form', true,")
      ..writeln("      'include_expected_goals', true,")
      ..writeln("      'recent_form_days_back', 180,")
      ..writeln("      'recent_form_matches', 5")
      ..writeln('    ),')
      ..writeln('    timeout_milliseconds := 300000')
      ..writeln('  ) as request_id;')
      ..writeln("  select cron.unschedule('$runNowSyncJob');")
      ..writeln(r'  $$')
      ..writeln(');')
      ..writeln();
  }

  cronBuffer
    ..writeln('select jobid, jobname, schedule, active')
    ..writeln('from cron.job')
    ..writeln("where jobname like 'api-football-%'")
    ..writeln('order by jobname;');

  runNowBuffer
    ..writeln('select jobid, jobname, schedule, active')
    ..writeln('from cron.job')
    ..writeln("where jobname like 'api-football-run-now-%'")
    ..writeln('order by jobname;');

  File(cronOutputPath).writeAsStringSync(cronBuffer.toString());
  File(runNowOutputPath).writeAsStringSync(runNowBuffer.toString());
  stdout.writeln('Wrote $cronOutputPath');
  stdout.writeln('Wrote $runNowOutputPath');
}

Map<String, String> _readDotEnv(File file) {
  if (!file.existsSync()) {
    return {};
  }
  final values = <String, String>{};
  for (final line in file.readAsLinesSync()) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) {
      continue;
    }
    final separator = trimmed.indexOf('=');
    if (separator <= 0) {
      continue;
    }
    final key = trimmed.substring(0, separator).trim();
    var value = trimmed.substring(separator + 1).trim();
    if (value.length >= 2 &&
        ((value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'")))) {
      value = value.substring(1, value.length - 1);
    }
    values[key] = value;
  }
  return values;
}

String _sql(String value) => value.replaceAll("'", "''");

String _runNowScheduleSql(int minuteOffset) {
  return "to_char(now() + interval '$minuteOffset minutes', 'MI HH24 * * *')";
}
